models:
  random_forest:
    experiment_name: "credit_risk_rf_experiment"
    primary_metric: "recall"

    hyperparameters:
      n_estimators: [100, 200, 300]
      max_depth: [10, 15, 20]
      min_samples_split: [10, 20, 30]
      min_samples_leaf: [5, 10, 15]
      max_features: ["sqrt", "log2", 0.4]
      bootstrap: [true]
      max_samples: [0.75, 0.8, 0.85]
      class_weight: ["balanced", "balanced_subsample", {0: 1, 1: 3}]
      criterion: ["gini", "entropy", "gini"]
      random_state: [42,42,42]
      n_jobs: [-1,-1,-1]
